# Generated by Django 5.0.3 on 2024-06-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
